

const list = [
  
  {
    id: 1,
    title: 'Almond Chocolate',
    author: 'Brand A',
    price: 150,
    img: 'https://m.media-amazon.com/images/I/71PcD9ImF1L.jpg',
    flavour: 'Almond',
    discount: '10% Off',
    category: 'Chocolate',
  },
  {
    id: 2,
    title: 'Bournavile Dark Chocolate',
    author: 'Brand B',
    price: 100,
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRM-Nz04b59fs92rekHcmUQztqEpeMuWa6KSw&s',
    flavour: 'Chocolate',
    discount: '15% Off',
    category: 'Chocolate',
  },
  {
    id: 3,
    title: 'Dairy Milk with Cashew',
    author: 'Brand C',
    price: 200,
    img: 'https://www.jiomart.com/images/product/original/490659556/cadbury-dairy-milk-silk-fruit-nut-chocolate-137-g-product-images-o490659556-p490659556-0-202210171819.jpg?im=Resize=(1000,1000)',
    flavour: 'Cashew',
    discount: '20% Off',
    category: 'Chocolate',
  },
  {
    id: 4,
    title: 'Almond Crunch',
    author: 'Brand D',
    price: 120,
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSmshUia3GmZ376N7EbpVww-IrSEMzJv_slyg&s',
    flavour: 'Almond',
    discount: '25% Off',
    category: 'Chocolate',
  },
  {
    id: 5,
    title: 'Dark Chocolate',
    author: 'Brand E',
    price: 180,
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCAFqodNpRwIUe5nAKIOSmDXU46s2EtVkYXA&s',
    flavour: 'Chocolate',
    discount: '30% Off',
    category: 'Chocolate',
  },
  {
    id: 6,
    title: 'KitKat',
    author: 'Brand E',
    price: 60,
    img: 'https://www.quickpantry.in/cdn/shop/products/kitkat-finger-wafer-chocolate-bar-18-5-g-quick-pantry_420x420.jpg?v=1710537954',
    flavour: 'Chocolate',
    discount: '30% Off',
    category: 'Chocolate',
  },
  {
    id: 7,
    title: 'Fabella with Cashew',
    author: 'Brand C',
    price: 200,
    img: 'https://b.zmtcdn.com/data/dish_photos/fab/ae16fcbc66f102d1ccd888fb6c1defab.jpeg',
    flavour: 'Cashew',
    discount: '20% Off',
    category: 'Chocolate',
  },
  {
    id: 8,
    title: 'Snickers',
    author: 'Brand C',
    price: 70,
    img: 'https://cococart.in/cdn/shop/products/254836272_94316c8f-ccfa-44d0-93f7-01d44563b0f3.jpg?v=1676355898&width=1946',
    flavour: 'Butterscotch',
    discount: '10% Off',
    category: 'Chocolate',
  },
  {
    id: 9,
    title: 'Luvlt',
    author: 'Brand C',
    price: 140, 
    amount: 1,
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8-5wk1denpGLrKPmoAv1jBVgKna3JxC-6DA&s',
    flavour: 'Butterscotch',
    discount: '20% Off',
    category: 'Chocolate',
  },
  {
    id: 10,
    title: 'Lays Classic',
    author: 'Lays',
    price: 200, 
    amount: 1,
    img: 'https://ik.imagekit.io/uko16m2rv/lays-paprika-crisps-red-130g-816737.jpg',
    flavour: 'Lays',
    discount: '10% Off',
    category: 'Chips',
  },
  {
    id: 11,
    title: 'Moong Dal',
    author: 'Haldiram',
    price: 60,
    img: 'https://ik.imagekit.io/uko16m2rv/moong_dal_1.jpg',
    flavour: 'Haldiram',
    discount: '15% Off',
    category: 'Chips',
  },
  {
    id: 12,
    title: 'Bingo',
    author: 'Lays',
    price: 55,
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTfV46eqr_TY25OewNnAXNVy9o_7HAFVN2tA&s',
    flavour: 'Lays',
    discount: '20% Off',
    category: 'Chips',
  },
  {
    id: 13 ,
    title: 'Aloo Bhujia',
    author: 'Haldiram',
    price: 65,
    img: 'https://www.bigbasket.com/media/uploads/p/l/263120_4-haldirams-namkeen-mixture.jpg',
    flavour: 'Haldiram',
    discount: '25% Off',
    category: 'Chips',
  },
  {
    id: 14 ,
    title: 'Kurkure',
    author: 'Kurkure',
    price: 60,
    img: 'https://m.media-amazon.com/images/I/71LyKlizpuL.jpg',
    flavour: 'Kurkure',
    discount: '15% Off',
    category: 'Chips',
  },
  {
    id: 15 ,
    title: 'TedheMedhe',
    author: 'Kurkure',
    price: 50,
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFbCkFXPIvlU0g-eeMyyx4qGmYYhQ-OOdz4w&s',
    flavour: 'Kurkure',
    discount: '10% Off',
    category: 'Chips',
  },
];
  
export default list;